import Foundation

/// The eight languages ConPaws ships, as the app spells them.
///
/// These match `SUPPORTED_LANGUAGES` in `src/lib/i18n.ts`, which is what ends up
/// in a snapshot's `localeIdentifier`.
enum ConPawsLanguage: String, CaseIterable, Sendable {
  case en
  case de
  case es
  case fr
  case nl
  case pl
  case ptBR = "pt-BR"
  case sv

  /// The language a snapshot's `localeIdentifier` names.
  ///
  /// Tolerant of spellings the app does not currently write -- `de_DE`, `PT-br`,
  /// a bare `pt` -- because the identifier crosses a process boundary and an
  /// unrecognised one must still render something rather than nothing.
  static func resolve(_ identifier: String) -> ConPawsLanguage {
    let normalized = identifier.replacingOccurrences(of: "_", with: "-").lowercased()
    if let exact = allCases.first(where: { $0.rawValue.lowercased() == normalized }) {
      return exact
    }
    let base = normalized.split(separator: "-").first.map(String.init) ?? normalized
    // Brazilian Portuguese is the only Portuguese in the app, so a regionless
    // `pt` belongs to it rather than falling through to English.
    if base == "pt" { return .ptBR }
    return allCases.first { $0.rawValue.lowercased() == base } ?? .en
  }
}

/// Which of a language's plural forms a count selects.
///
/// Only `few` needs explaining: Polish inflects 2-4 differently from 5 and up,
/// so "2 godziny" and "5 godzin" are not the same word. Every other language
/// here has the usual singular/plural pair and leaves `few` equal to `other`.
enum ConPawsPluralForm: Sendable {
  case one
  case few
  case other
}

extension ConPawsLanguage {
  func pluralForm(_ count: Int) -> ConPawsPluralForm {
    let value = abs(count)
    guard self == .pl else { return value == 1 ? .one : .other }
    if value == 1 { return .one }
    let mod10 = value % 10
    let mod100 = value % 100
    if (2...4).contains(mod10), !(12...14).contains(mod100) { return .few }
    return .other
  }
}

/// One countable noun in every form the eight languages need.
///
/// The templates carry `%@` rather than `%d` so every substitution in this file
/// goes through the same string-only path: a numeric format specifier and a
/// Swift `Int` disagree about width, and mixing the two is how a format string
/// starts reading the wrong bytes.
struct ConPawsPluralUnit: Sendable {
  let one: String
  let few: String
  let other: String

  /// The same noun in whatever case the language's "in" preposition governs.
  ///
  /// German takes the dative, so a countdown says "In 3 Tagen" where the noun
  /// on its own is "3 Tage". Polish takes the accusative, so "Za 1 godzinę"
  /// where the noun on its own is "1 godzina". Languages that inflect neither
  /// leave these equal to the plain forms, which is the default.
  let obliqueOne: String
  let obliqueFew: String
  let obliqueOther: String

  init(
    one: String,
    few: String? = nil,
    other: String,
    obliqueOne: String? = nil,
    obliqueFew: String? = nil,
    obliqueOther: String? = nil
  ) {
    self.one = one
    self.few = few ?? other
    self.other = other
    self.obliqueOne = obliqueOne ?? one
    self.obliqueFew = obliqueFew ?? few ?? other
    self.obliqueOther = obliqueOther ?? other
  }

  func template(for form: ConPawsPluralForm, oblique: Bool) -> String {
    switch form {
    case .one: oblique ? obliqueOne : one
    case .few: oblique ? obliqueFew : few
    case .other: oblique ? obliqueOther : other
    }
  }
}

/// Every word these targets render, in the app's language rather than the
/// phone's.
///
/// This is a Swift table, not a `.strings` or `.xcstrings` resource, for two
/// reasons that both have to hold before resources would be an option:
///
/// - `@bacons/apple-targets` generates the Xcode project and has no
///   localization support at all. It writes no variant groups and no
///   `knownRegions`, and the project it produces is regenerated by prebuild, so
///   nothing checked in here can add a region to it.
/// - A widget or complication resolves `NSLocalizedString` against the *device*
///   language through `Bundle.main`. ConPaws' language is an in-app setting
///   that need not match the device, and it travels here as the snapshot's
///   `localeIdentifier`. Even with resources in place, rendering the app's
///   language would mean loading a specific `.lproj` bundle by that identifier
///   by hand -- which is this table, with a silent-fallback failure mode added.
///
/// The strings the *system* renders -- the widget gallery entry, the
/// configuration intent, `CFBundleDisplayName` -- are deliberately not here.
/// Those follow the device language by design and do need real resources.
struct ConPawsStrings: Sendable {
  let language: ConPawsLanguage

  // MARK: Countdown vocabulary

  let now: String
  let startingSoon: String
  let today: String
  let tomorrow: String
  /// Wraps a duration into a countdown, as in "In 3 hours".
  let inFormat: String
  let hoursUnit: ConPawsPluralUnit
  let daysUnit: ConPawsPluralUnit
  let monthsUnit: ConPawsPluralUnit
  let minutesUnit: ConPawsPluralUnit
  let eventsUnit: ConPawsPluralUnit
  let compactNow: String
  let compactSoon: String
  let compactHoursFormat: String
  let compactDaysFormat: String
  let compactMonthsFormat: String
  /// Wraps a duration for VoiceOver, as in "3 days, 4 hours remaining".
  let remainingFormat: String

  // MARK: Eyebrows, already in the case they are drawn in

  let comingUpCaps: String
  let nextCaps: String
  let whereCaps: String
  let nowCaps: String
  let leaveCaps: String
  let leaveInCaps: String
  let forCaps: String
  let noEventsCaps: String

  // MARK: iPhone widget

  let locationNotSet: String
  let nowEventFormat: String
  let leaveIn: String
  let freeNow: String
  let noUpcomingEvents: String
  let addConventionHint: String
  let addScheduleHint: String
  let addConvention: String
  let leaveForA11yFormat: String
  let nextA11yFormat: String
  let inlineLeaveFormat: String
  /// Whether the countdown reads correctly lower-cased mid-sentence.
  ///
  /// False for German, where "In 3 Stunden" carries a capitalised noun that
  /// lower-casing would break. German phrases its inline leave line around a
  /// colon instead, so the countdown can keep its own capitals.
  let lowercasesInlineCountdown: Bool

  // MARK: Watch complication

  let syncFromPhone: String
  let comingUpA11yFormat: String
  let leaveWithCurrentA11yFormat: String
  let leaveA11yFormat: String
  let nextEventA11yFormat: String

  // MARK: Watch app

  let noScheduleTitle: String
  let noScheduleMessage: String
  let nothingUpcomingTitle: String
  let nothingUpcomingMessage: String
  let untilTheConvention: String
  let comingUpTitle: String
  let scheduleTitle: String
  let eventTitle: String
  let laterLabel: String
  let scheduledLabel: String
  let noMoreEventsToday: String
  let noEventsTodayTitle: String
  let noEventsTodayMessage: String
  let minutesBeforeFormat: String
  let leaveReminderFormat: String
  let savedSchedule: String
  let savedScheduleA11y: String
}

// MARK: - Substitution

extension ConPawsStrings {
  /// The table for a snapshot's `localeIdentifier`.
  static func resolve(_ localeIdentifier: String) -> ConPawsStrings {
    table(for: ConPawsLanguage.resolve(localeIdentifier))
  }

  /// English, for previews and for the debug self-checks that assert on exact
  /// wording. Reading the device's language there would fail the assertions on
  /// a German Mac for the wrong reason.
  static let english = table(for: .en)

  private func substituting(_ template: String, _ arguments: [String]) -> String {
    String(format: template, arguments: arguments.map { $0 as CVarArg })
  }

  func text(_ template: String, _ arguments: String...) -> String {
    substituting(template, arguments)
  }

  private func count(
    _ unit: ConPawsPluralUnit,
    _ value: Int,
    oblique: Bool = false
  ) -> String {
    let template = unit.template(for: language.pluralForm(value), oblique: oblique)
    return substituting(template, [String(value)])
  }

  func hours(_ value: Int) -> String { count(hoursUnit, value) }
  func days(_ value: Int) -> String { count(daysUnit, value) }
  func months(_ value: Int) -> String { count(monthsUnit, value) }
  func minutes(_ value: Int) -> String { count(minutesUnit, value) }
  func events(_ value: Int) -> String { count(eventsUnit, value) }

  func inHours(_ value: Int) -> String {
    text(inFormat, count(hoursUnit, value, oblique: true))
  }

  func inDays(_ value: Int) -> String {
    text(inFormat, count(daysUnit, value, oblique: true))
  }

  func inMonths(_ value: Int) -> String {
    text(inFormat, count(monthsUnit, value, oblique: true))
  }

  func compactHours(_ value: Int) -> String { text(compactHoursFormat, String(value)) }
  func compactDays(_ value: Int) -> String { text(compactDaysFormat, String(value)) }
  func compactMonths(_ value: Int) -> String { text(compactMonthsFormat, String(value)) }

  /// Two units side by side, as VoiceOver reads a countdown.
  func duration(_ first: String, _ second: String) -> String {
    "\(first), \(second)"
  }

  /// The same pair, phrased as time left.
  func remaining(_ duration: String) -> String {
    text(remainingFormat, duration)
  }

  /// A countdown placed inside a sentence, cased so it still reads as one.
  func midSentenceCountdown(_ label: String) -> String {
    lowercasesInlineCountdown ? label.lowercased() : label
  }
}

// MARK: - Translations

extension ConPawsStrings {
  static func table(for language: ConPawsLanguage) -> ConPawsStrings {
    switch language {
    case .en: en
    case .de: de
    case .es: es
    case .fr: fr
    case .nl: nl
    case .pl: pl
    case .ptBR: ptBR
    case .sv: sv
    }
  }

  private static let en = ConPawsStrings(
    language: .en,
    now: "Now",
    startingSoon: "Starting soon",
    today: "Today",
    tomorrow: "Tomorrow",
    inFormat: "In %@",
    hoursUnit: ConPawsPluralUnit(one: "%@ hour", other: "%@ hours"),
    daysUnit: ConPawsPluralUnit(one: "%@ day", other: "%@ days"),
    monthsUnit: ConPawsPluralUnit(one: "%@ month", other: "%@ months"),
    minutesUnit: ConPawsPluralUnit(one: "%@ minute", other: "%@ minutes"),
    eventsUnit: ConPawsPluralUnit(one: "%@ event", other: "%@ events"),
    compactNow: "Now",
    compactSoon: "Soon",
    compactHoursFormat: "%@h",
    compactDaysFormat: "%@d",
    compactMonthsFormat: "%@mo",
    remainingFormat: "%@ remaining",
    comingUpCaps: "COMING UP",
    nextCaps: "NEXT",
    whereCaps: "WHERE",
    nowCaps: "NOW",
    leaveCaps: "LEAVE",
    leaveInCaps: "LEAVE IN",
    forCaps: "FOR",
    noEventsCaps: "NO EVENTS",
    locationNotSet: "Location not set",
    nowEventFormat: "Now: %@",
    leaveIn: "Leave in",
    freeNow: "Free now",
    noUpcomingEvents: "No upcoming events",
    addConventionHint: "Add a convention in ConPaws.",
    addScheduleHint: "Add or import a schedule in ConPaws.",
    addConvention: "Add a convention",
    leaveForA11yFormat: "Leave for %1$@, %2$@",
    nextA11yFormat: "Next: %1$@, %2$@",
    inlineLeaveFormat: "Leave %@",
    lowercasesInlineCountdown: true,
    syncFromPhone: "Sync a convention from iPhone",
    comingUpA11yFormat: "Coming up, %1$@, %2$@",
    leaveWithCurrentA11yFormat: "Leave in %1$@. Current event: %2$@. Next event: %3$@, starts %4$@.",
    leaveA11yFormat: "Leave in %1$@ for %2$@, starts %3$@.",
    nextEventA11yFormat: "Next event: %1$@, starts %2$@",
    noScheduleTitle: "No schedule yet",
    noScheduleMessage: "Open ConPaws on your iPhone to sync a convention.",
    nothingUpcomingTitle: "Nothing upcoming",
    nothingUpcomingMessage: "Your saved conventions have ended.",
    untilTheConvention: "Until the convention",
    comingUpTitle: "Coming Up",
    scheduleTitle: "Schedule",
    eventTitle: "Event",
    laterLabel: "Later",
    scheduledLabel: "Scheduled",
    noMoreEventsToday: "No more events today",
    noEventsTodayTitle: "No events today",
    noEventsTodayMessage: "Your next saved event is on another day.",
    minutesBeforeFormat: "%@ min before",
    leaveReminderFormat: "Leave reminder %@",
    savedSchedule: "Saved schedule",
    savedScheduleA11y: "Showing the latest schedule saved from your iPhone"
  )

  private static let de = ConPawsStrings(
    language: .de,
    now: "Jetzt",
    startingSoon: "Beginnt bald",
    today: "Heute",
    tomorrow: "Morgen",
    inFormat: "In %@",
    hoursUnit: ConPawsPluralUnit(one: "%@ Stunde", other: "%@ Stunden"),
    daysUnit: ConPawsPluralUnit(one: "%@ Tag", other: "%@ Tage", obliqueOther: "%@ Tagen"),
    monthsUnit: ConPawsPluralUnit(
      one: "%@ Monat",
      other: "%@ Monate",
      obliqueOther: "%@ Monaten"
    ),
    minutesUnit: ConPawsPluralUnit(one: "%@ Minute", other: "%@ Minuten"),
    eventsUnit: ConPawsPluralUnit(one: "%@ Event", other: "%@ Events"),
    compactNow: "Jetzt",
    compactSoon: "Bald",
    compactHoursFormat: "%@ Std.",
    compactDaysFormat: "%@ T",
    compactMonthsFormat: "%@ Mon.",
    remainingFormat: "noch %@",
    comingUpCaps: "DEMNÄCHST",
    nextCaps: "NÄCHSTES",
    whereCaps: "WO",
    nowCaps: "JETZT",
    leaveCaps: "LOS",
    leaveInCaps: "LOS IN",
    forCaps: "FÜR",
    noEventsCaps: "KEINE EVENTS",
    locationNotSet: "Kein Ort angegeben",
    nowEventFormat: "Jetzt: %@",
    leaveIn: "Losgehen in",
    freeNow: "Gerade frei",
    noUpcomingEvents: "Keine anstehenden Events",
    addConventionHint: "Füge in ConPaws eine Convention hinzu.",
    addScheduleHint: "Füge in ConPaws einen Zeitplan hinzu oder importiere einen.",
    addConvention: "Convention hinzufügen",
    leaveForA11yFormat: "Losgehen zu %1$@, %2$@",
    nextA11yFormat: "Als Nächstes: %1$@, %2$@",
    inlineLeaveFormat: "Losgehen: %@",
    lowercasesInlineCountdown: false,
    syncFromPhone: "Convention vom iPhone synchronisieren",
    comingUpA11yFormat: "Demnächst, %1$@, %2$@",
    leaveWithCurrentA11yFormat: "Losgehen in %1$@. Aktuelles Event: %2$@. Nächstes Event: %3$@, beginnt %4$@.",
    leaveA11yFormat: "Losgehen in %1$@ zu %2$@, beginnt %3$@.",
    nextEventA11yFormat: "Nächstes Event: %1$@, beginnt %2$@",
    noScheduleTitle: "Noch kein Zeitplan",
    noScheduleMessage: "Öffne ConPaws auf deinem iPhone, um eine Convention zu synchronisieren.",
    nothingUpcomingTitle: "Nichts geplant",
    nothingUpcomingMessage: "Deine gespeicherten Conventions sind vorbei.",
    untilTheConvention: "Bis zur Convention",
    comingUpTitle: "Demnächst",
    scheduleTitle: "Zeitplan",
    eventTitle: "Event",
    laterLabel: "Später",
    scheduledLabel: "Geplant",
    noMoreEventsToday: "Heute keine weiteren Events",
    noEventsTodayTitle: "Heute keine Events",
    noEventsTodayMessage: "Dein nächstes gespeichertes Event ist an einem anderen Tag.",
    minutesBeforeFormat: "%@ Min. vorher",
    leaveReminderFormat: "Erinnerung: %@",
    savedSchedule: "Gespeicherter Zeitplan",
    savedScheduleA11y: "Zeigt den zuletzt von deinem iPhone gespeicherten Zeitplan"
  )

  private static let es = ConPawsStrings(
    language: .es,
    now: "Ahora",
    startingSoon: "Empieza pronto",
    today: "Hoy",
    tomorrow: "Mañana",
    inFormat: "En %@",
    hoursUnit: ConPawsPluralUnit(one: "%@ hora", other: "%@ horas"),
    daysUnit: ConPawsPluralUnit(one: "%@ día", other: "%@ días"),
    monthsUnit: ConPawsPluralUnit(one: "%@ mes", other: "%@ meses"),
    minutesUnit: ConPawsPluralUnit(one: "%@ minuto", other: "%@ minutos"),
    eventsUnit: ConPawsPluralUnit(one: "%@ evento", other: "%@ eventos"),
    compactNow: "Ahora",
    compactSoon: "Pronto",
    compactHoursFormat: "%@ h",
    compactDaysFormat: "%@ d",
    compactMonthsFormat: "%@ m",
    remainingFormat: "faltan %@",
    comingUpCaps: "PRÓXIMAMENTE",
    nextCaps: "SIGUIENTE",
    whereCaps: "DÓNDE",
    nowCaps: "AHORA",
    leaveCaps: "SALIR",
    leaveInCaps: "SALIR EN",
    forCaps: "PARA",
    noEventsCaps: "SIN EVENTOS",
    locationNotSet: "Sin ubicación",
    nowEventFormat: "Ahora: %@",
    leaveIn: "Salir en",
    freeNow: "Ahora libre",
    noUpcomingEvents: "Sin eventos próximos",
    addConventionHint: "Añade una convención en ConPaws.",
    addScheduleHint: "Añade o importa un horario en ConPaws.",
    addConvention: "Añadir una convención",
    leaveForA11yFormat: "Salir hacia %1$@, %2$@",
    nextA11yFormat: "Siguiente: %1$@, %2$@",
    inlineLeaveFormat: "Salir %@",
    lowercasesInlineCountdown: true,
    syncFromPhone: "Sincroniza una convención desde el iPhone",
    comingUpA11yFormat: "Próximamente, %1$@, %2$@",
    leaveWithCurrentA11yFormat: "Salir en %1$@. Evento actual: %2$@. Próximo evento: %3$@, empieza %4$@.",
    leaveA11yFormat: "Salir en %1$@ hacia %2$@, empieza %3$@.",
    nextEventA11yFormat: "Próximo evento: %1$@, empieza %2$@",
    noScheduleTitle: "Aún sin horario",
    noScheduleMessage: "Abre ConPaws en tu iPhone para sincronizar una convención.",
    nothingUpcomingTitle: "Nada próximo",
    nothingUpcomingMessage: "Tus convenciones guardadas han terminado.",
    untilTheConvention: "Hasta la convención",
    comingUpTitle: "Próximamente",
    scheduleTitle: "Horario",
    eventTitle: "Evento",
    laterLabel: "Más tarde",
    scheduledLabel: "Programado",
    noMoreEventsToday: "No hay más eventos hoy",
    noEventsTodayTitle: "Sin eventos hoy",
    noEventsTodayMessage: "Tu próximo evento guardado es otro día.",
    minutesBeforeFormat: "%@ min antes",
    leaveReminderFormat: "Recordatorio de salida %@",
    savedSchedule: "Horario guardado",
    savedScheduleA11y: "Mostrando el último horario guardado desde tu iPhone"
  )

  private static let fr = ConPawsStrings(
    language: .fr,
    now: "Maintenant",
    startingSoon: "Commence bientôt",
    today: "Aujourd’hui",
    tomorrow: "Demain",
    inFormat: "Dans %@",
    hoursUnit: ConPawsPluralUnit(one: "%@ heure", other: "%@ heures"),
    daysUnit: ConPawsPluralUnit(one: "%@ jour", other: "%@ jours"),
    monthsUnit: ConPawsPluralUnit(one: "%@ mois", other: "%@ mois"),
    minutesUnit: ConPawsPluralUnit(one: "%@ minute", other: "%@ minutes"),
    eventsUnit: ConPawsPluralUnit(one: "%@ événement", other: "%@ événements"),
    compactNow: "Maint.",
    compactSoon: "Bientôt",
    compactHoursFormat: "%@ h",
    compactDaysFormat: "%@ j",
    compactMonthsFormat: "%@ mois",
    remainingFormat: "%@ restants",
    comingUpCaps: "À VENIR",
    nextCaps: "SUIVANT",
    whereCaps: "OÙ",
    nowCaps: "MAINTENANT",
    leaveCaps: "PARTIR",
    leaveInCaps: "PARTIR DANS",
    forCaps: "POUR",
    noEventsCaps: "AUCUN ÉVÉNEMENT",
    locationNotSet: "Lieu non défini",
    nowEventFormat: "Maintenant : %@",
    leaveIn: "Partir dans",
    freeNow: "Libre maintenant",
    noUpcomingEvents: "Aucun événement à venir",
    addConventionHint: "Ajoutez une convention dans ConPaws.",
    addScheduleHint: "Ajoutez ou importez un programme dans ConPaws.",
    addConvention: "Ajouter une convention",
    leaveForA11yFormat: "Partir pour %1$@, %2$@",
    nextA11yFormat: "Suivant : %1$@, %2$@",
    inlineLeaveFormat: "Partir %@",
    lowercasesInlineCountdown: true,
    syncFromPhone: "Synchronisez une convention depuis l’iPhone",
    comingUpA11yFormat: "À venir, %1$@, %2$@",
    leaveWithCurrentA11yFormat: "Partir dans %1$@. Événement en cours : %2$@. Prochain événement : %3$@, commence %4$@.",
    leaveA11yFormat: "Partir dans %1$@ pour %2$@, commence %3$@.",
    nextEventA11yFormat: "Prochain événement : %1$@, commence %2$@",
    noScheduleTitle: "Pas encore de programme",
    noScheduleMessage: "Ouvrez ConPaws sur votre iPhone pour synchroniser une convention.",
    nothingUpcomingTitle: "Rien à venir",
    nothingUpcomingMessage: "Vos conventions enregistrées sont terminées.",
    untilTheConvention: "Avant la convention",
    comingUpTitle: "À venir",
    scheduleTitle: "Programme",
    eventTitle: "Événement",
    laterLabel: "Plus tard",
    scheduledLabel: "Programmé",
    noMoreEventsToday: "Plus d’événements aujourd’hui",
    noEventsTodayTitle: "Aucun événement aujourd’hui",
    noEventsTodayMessage: "Votre prochain événement enregistré a lieu un autre jour.",
    minutesBeforeFormat: "%@ min avant",
    leaveReminderFormat: "Rappel de départ %@",
    savedSchedule: "Programme enregistré",
    savedScheduleA11y: "Affiche le dernier programme enregistré depuis votre iPhone"
  )

  private static let nl = ConPawsStrings(
    language: .nl,
    now: "Nu",
    startingSoon: "Begint binnenkort",
    today: "Vandaag",
    tomorrow: "Morgen",
    inFormat: "Over %@",
    hoursUnit: ConPawsPluralUnit(one: "%@ uur", other: "%@ uur"),
    daysUnit: ConPawsPluralUnit(one: "%@ dag", other: "%@ dagen"),
    monthsUnit: ConPawsPluralUnit(one: "%@ maand", other: "%@ maanden"),
    minutesUnit: ConPawsPluralUnit(one: "%@ minuut", other: "%@ minuten"),
    eventsUnit: ConPawsPluralUnit(one: "%@ evenement", other: "%@ evenementen"),
    compactNow: "Nu",
    compactSoon: "Zo",
    compactHoursFormat: "%@ u",
    compactDaysFormat: "%@ d",
    compactMonthsFormat: "%@ mnd",
    remainingFormat: "nog %@",
    comingUpCaps: "BINNENKORT",
    nextCaps: "VOLGENDE",
    whereCaps: "WAAR",
    nowCaps: "NU",
    leaveCaps: "VERTREK",
    leaveInCaps: "VERTREK OVER",
    forCaps: "VOOR",
    noEventsCaps: "GEEN EVENEMENTEN",
    locationNotSet: "Geen locatie",
    nowEventFormat: "Nu: %@",
    leaveIn: "Vertrekken over",
    freeNow: "Nu vrij",
    noUpcomingEvents: "Geen aankomende evenementen",
    addConventionHint: "Voeg een conventie toe in ConPaws.",
    addScheduleHint: "Voeg een rooster toe of importeer er een in ConPaws.",
    addConvention: "Conventie toevoegen",
    leaveForA11yFormat: "Vertrekken naar %1$@, %2$@",
    nextA11yFormat: "Volgende: %1$@, %2$@",
    inlineLeaveFormat: "Vertrekken %@",
    lowercasesInlineCountdown: true,
    syncFromPhone: "Synchroniseer een conventie vanaf je iPhone",
    comingUpA11yFormat: "Binnenkort, %1$@, %2$@",
    leaveWithCurrentA11yFormat: "Vertrekken over %1$@. Huidig evenement: %2$@. Volgend evenement: %3$@, begint %4$@.",
    leaveA11yFormat: "Vertrekken over %1$@ naar %2$@, begint %3$@.",
    nextEventA11yFormat: "Volgend evenement: %1$@, begint %2$@",
    noScheduleTitle: "Nog geen rooster",
    noScheduleMessage: "Open ConPaws op je iPhone om een conventie te synchroniseren.",
    nothingUpcomingTitle: "Niets aankomends",
    nothingUpcomingMessage: "Je opgeslagen conventies zijn afgelopen.",
    untilTheConvention: "Tot de conventie",
    comingUpTitle: "Binnenkort",
    scheduleTitle: "Rooster",
    eventTitle: "Evenement",
    laterLabel: "Later",
    scheduledLabel: "Gepland",
    noMoreEventsToday: "Geen evenementen meer vandaag",
    noEventsTodayTitle: "Geen evenementen vandaag",
    noEventsTodayMessage: "Je volgende opgeslagen evenement is op een andere dag.",
    minutesBeforeFormat: "%@ min van tevoren",
    leaveReminderFormat: "Vertrekherinnering %@",
    savedSchedule: "Opgeslagen rooster",
    savedScheduleA11y: "Toont het laatste rooster dat vanaf je iPhone is opgeslagen"
  )

  private static let pl = ConPawsStrings(
    language: .pl,
    now: "Teraz",
    startingSoon: "Zaczyna się wkrótce",
    today: "Dzisiaj",
    tomorrow: "Jutro",
    inFormat: "Za %@",
    hoursUnit: ConPawsPluralUnit(
      one: "%@ godzina",
      few: "%@ godziny",
      other: "%@ godzin",
      obliqueOne: "%@ godzinę"
    ),
    daysUnit: ConPawsPluralUnit(one: "%@ dzień", few: "%@ dni", other: "%@ dni"),
    monthsUnit: ConPawsPluralUnit(one: "%@ miesiąc", few: "%@ miesiące", other: "%@ miesięcy"),
    minutesUnit: ConPawsPluralUnit(
      one: "%@ minuta",
      few: "%@ minuty",
      other: "%@ minut",
      obliqueOne: "%@ minutę"
    ),
    eventsUnit: ConPawsPluralUnit(one: "%@ wydarzenie", few: "%@ wydarzenia", other: "%@ wydarzeń"),
    compactNow: "Teraz",
    compactSoon: "Wkrótce",
    compactHoursFormat: "%@ godz.",
    compactDaysFormat: "%@ dn.",
    compactMonthsFormat: "%@ mies.",
    remainingFormat: "pozostało %@",
    comingUpCaps: "WKRÓTCE",
    nextCaps: "NASTĘPNE",
    whereCaps: "GDZIE",
    nowCaps: "TERAZ",
    leaveCaps: "WYJŚCIE",
    leaveInCaps: "WYJŚCIE ZA",
    forCaps: "NA",
    noEventsCaps: "BRAK WYDARZEŃ",
    locationNotSet: "Brak lokalizacji",
    nowEventFormat: "Teraz: %@",
    leaveIn: "Wyjście za",
    freeNow: "Teraz wolne",
    noUpcomingEvents: "Brak nadchodzących wydarzeń",
    addConventionHint: "Dodaj konwent w ConPaws.",
    addScheduleHint: "Dodaj lub zaimportuj harmonogram w ConPaws.",
    addConvention: "Dodaj konwent",
    leaveForA11yFormat: "Wyjście na %1$@, %2$@",
    nextA11yFormat: "Następne: %1$@, %2$@",
    inlineLeaveFormat: "Wyjście %@",
    lowercasesInlineCountdown: true,
    syncFromPhone: "Zsynchronizuj konwent z iPhone’a",
    comingUpA11yFormat: "Wkrótce, %1$@, %2$@",
    leaveWithCurrentA11yFormat: "Wyjście za %1$@. Bieżące wydarzenie: %2$@. Następne wydarzenie: %3$@, zaczyna się %4$@.",
    leaveA11yFormat: "Wyjście za %1$@ na %2$@, zaczyna się %3$@.",
    nextEventA11yFormat: "Następne wydarzenie: %1$@, zaczyna się %2$@",
    noScheduleTitle: "Brak harmonogramu",
    noScheduleMessage: "Otwórz ConPaws na iPhonie, aby zsynchronizować konwent.",
    nothingUpcomingTitle: "Nic nadchodzącego",
    nothingUpcomingMessage: "Twoje zapisane konwenty się zakończyły.",
    untilTheConvention: "Do konwentu",
    comingUpTitle: "Wkrótce",
    scheduleTitle: "Harmonogram",
    eventTitle: "Wydarzenie",
    laterLabel: "Później",
    scheduledLabel: "Zaplanowane",
    noMoreEventsToday: "Brak dalszych wydarzeń dzisiaj",
    noEventsTodayTitle: "Brak wydarzeń dzisiaj",
    noEventsTodayMessage: "Twoje następne zapisane wydarzenie jest innego dnia.",
    minutesBeforeFormat: "%@ min wcześniej",
    leaveReminderFormat: "Przypomnienie o wyjściu %@",
    savedSchedule: "Zapisany harmonogram",
    savedScheduleA11y: "Pokazuje ostatni harmonogram zapisany z iPhone’a"
  )

  private static let ptBR = ConPawsStrings(
    language: .ptBR,
    now: "Agora",
    startingSoon: "Começa em breve",
    today: "Hoje",
    tomorrow: "Amanhã",
    inFormat: "Em %@",
    hoursUnit: ConPawsPluralUnit(one: "%@ hora", other: "%@ horas"),
    daysUnit: ConPawsPluralUnit(one: "%@ dia", other: "%@ dias"),
    monthsUnit: ConPawsPluralUnit(one: "%@ mês", other: "%@ meses"),
    minutesUnit: ConPawsPluralUnit(one: "%@ minuto", other: "%@ minutos"),
    eventsUnit: ConPawsPluralUnit(one: "%@ evento", other: "%@ eventos"),
    compactNow: "Agora",
    compactSoon: "Em breve",
    compactHoursFormat: "%@ h",
    compactDaysFormat: "%@ d",
    compactMonthsFormat: "%@ m",
    remainingFormat: "faltam %@",
    comingUpCaps: "EM BREVE",
    nextCaps: "A SEGUIR",
    whereCaps: "ONDE",
    nowCaps: "AGORA",
    leaveCaps: "SAIR",
    leaveInCaps: "SAIR EM",
    forCaps: "PARA",
    noEventsCaps: "SEM EVENTOS",
    locationNotSet: "Local não definido",
    nowEventFormat: "Agora: %@",
    leaveIn: "Sair em",
    freeNow: "Livre agora",
    noUpcomingEvents: "Nenhum evento a seguir",
    addConventionHint: "Adicione uma convenção no ConPaws.",
    addScheduleHint: "Adicione ou importe uma programação no ConPaws.",
    addConvention: "Adicionar uma convenção",
    leaveForA11yFormat: "Sair para %1$@, %2$@",
    nextA11yFormat: "A seguir: %1$@, %2$@",
    inlineLeaveFormat: "Sair %@",
    lowercasesInlineCountdown: true,
    syncFromPhone: "Sincronize uma convenção do iPhone",
    comingUpA11yFormat: "Em breve, %1$@, %2$@",
    leaveWithCurrentA11yFormat: "Sair em %1$@. Evento atual: %2$@. Próximo evento: %3$@, começa %4$@.",
    leaveA11yFormat: "Sair em %1$@ para %2$@, começa %3$@.",
    nextEventA11yFormat: "Próximo evento: %1$@, começa %2$@",
    noScheduleTitle: "Ainda sem programação",
    noScheduleMessage: "Abra o ConPaws no seu iPhone para sincronizar uma convenção.",
    nothingUpcomingTitle: "Nada a seguir",
    nothingUpcomingMessage: "Suas convenções salvas terminaram.",
    untilTheConvention: "Até a convenção",
    comingUpTitle: "Em breve",
    scheduleTitle: "Programação",
    eventTitle: "Evento",
    laterLabel: "Mais tarde",
    scheduledLabel: "Agendado",
    noMoreEventsToday: "Sem mais eventos hoje",
    noEventsTodayTitle: "Nenhum evento hoje",
    noEventsTodayMessage: "Seu próximo evento salvo é em outro dia.",
    minutesBeforeFormat: "%@ min antes",
    leaveReminderFormat: "Lembrete de saída %@",
    savedSchedule: "Programação salva",
    savedScheduleA11y: "Mostrando a última programação salva do seu iPhone"
  )

  private static let sv = ConPawsStrings(
    language: .sv,
    now: "Nu",
    startingSoon: "Börjar snart",
    today: "I dag",
    tomorrow: "I morgon",
    inFormat: "Om %@",
    hoursUnit: ConPawsPluralUnit(one: "%@ timme", other: "%@ timmar"),
    daysUnit: ConPawsPluralUnit(one: "%@ dag", other: "%@ dagar"),
    monthsUnit: ConPawsPluralUnit(one: "%@ månad", other: "%@ månader"),
    minutesUnit: ConPawsPluralUnit(one: "%@ minut", other: "%@ minuter"),
    eventsUnit: ConPawsPluralUnit(one: "%@ evenemang", other: "%@ evenemang"),
    compactNow: "Nu",
    compactSoon: "Snart",
    compactHoursFormat: "%@ tim",
    compactDaysFormat: "%@ d",
    compactMonthsFormat: "%@ mån",
    remainingFormat: "%@ kvar",
    comingUpCaps: "KOMMANDE",
    nextCaps: "HÄRNÄST",
    whereCaps: "VAR",
    nowCaps: "NU",
    leaveCaps: "GÅ",
    leaveInCaps: "GÅ OM",
    forCaps: "TILL",
    noEventsCaps: "INGA EVENEMANG",
    locationNotSet: "Ingen plats angiven",
    nowEventFormat: "Nu: %@",
    leaveIn: "Gå om",
    freeNow: "Ledig nu",
    noUpcomingEvents: "Inga kommande evenemang",
    addConventionHint: "Lägg till ett konvent i ConPaws.",
    addScheduleHint: "Lägg till eller importera ett schema i ConPaws.",
    addConvention: "Lägg till ett konvent",
    leaveForA11yFormat: "Gå till %1$@, %2$@",
    nextA11yFormat: "Härnäst: %1$@, %2$@",
    inlineLeaveFormat: "Gå %@",
    lowercasesInlineCountdown: true,
    syncFromPhone: "Synka ett konvent från iPhone",
    comingUpA11yFormat: "Kommande, %1$@, %2$@",
    leaveWithCurrentA11yFormat: "Gå om %1$@. Aktuellt evenemang: %2$@. Nästa evenemang: %3$@, börjar %4$@.",
    leaveA11yFormat: "Gå om %1$@ till %2$@, börjar %3$@.",
    nextEventA11yFormat: "Nästa evenemang: %1$@, börjar %2$@",
    noScheduleTitle: "Inget schema ännu",
    noScheduleMessage: "Öppna ConPaws på din iPhone för att synka ett konvent.",
    nothingUpcomingTitle: "Inget kommande",
    nothingUpcomingMessage: "Dina sparade konvent är slut.",
    untilTheConvention: "Till konventet",
    comingUpTitle: "Kommande",
    scheduleTitle: "Schema",
    eventTitle: "Evenemang",
    laterLabel: "Senare",
    scheduledLabel: "Schemalagt",
    noMoreEventsToday: "Inga fler evenemang i dag",
    noEventsTodayTitle: "Inga evenemang i dag",
    noEventsTodayMessage: "Ditt nästa sparade evenemang är en annan dag.",
    minutesBeforeFormat: "%@ min innan",
    leaveReminderFormat: "Påminnelse om att gå %@",
    savedSchedule: "Sparat schema",
    savedScheduleA11y: "Visar det senaste schemat som sparats från din iPhone"
  )

}
