import { getCloudflareContext } from "@opennextjs/cloudflare";
import { drizzle } from "drizzle-orm/d1";
import { catalogSchema } from "../db/schema";

export interface AdminBindings {
  CATALOG_DB?: D1Database;
  /**
   * `local` only in an ignored `.dev.vars` file. The production deploy always
   * binds `production`, and anything other than `local` is treated as
   * production: secure cookies, no development shortcuts.
   */
  ADMIN_RUNTIME_ENV?: "local" | "production";
  /** Local development only: act as this address without a sign-in code. */
  ADMIN_DEV_EMAIL?: string;
  /** Keys the HMAC that stores sign-in codes. Generated by the deploy. */
  ADMIN_AUTH_SECRET?: string;
  /** The console's own origin, used in emailed links. */
  ADMIN_PUBLIC_URL?: string;
  /** The address sign-in and invite emails come from. */
  ADMIN_EMAIL_FROM?: string;
  /** Cloudflare Email Service. */
  ADMIN_EMAIL?: SendEmail;
  /** Per-network limit on code requests and code checks. */
  ADMIN_SIGN_IN_LIMITER?: RateLimit;
}

export async function getAdminContext() {
  const context = await getCloudflareContext({ async: true });
  return {
    env: context.env as CloudflareEnv & AdminBindings,
    ctx: context.ctx as Pick<ExecutionContext, "waitUntil"> | undefined,
  };
}

export async function getAdminBindings() {
  return (await getAdminContext()).env;
}

export async function getCatalogDatabase() {
  const binding = (await getAdminBindings()).CATALOG_DB;
  if (!binding) throw new Error("The catalog database binding is missing.");
  return binding;
}

export async function getCatalogDb() {
  return drizzle(await getCatalogDatabase(), { schema: catalogSchema });
}
