const { withGradleProperties } = require("expo/config-plugins");

/**
 * Turns on R8 for Android release builds.
 *
 * The generated `android/app/build.gradle` already reads the switch:
 *
 *     def enableMinifyInReleaseBuilds =
 *       (findProperty('android.enableMinifyInReleaseBuilds') ?: false).toBoolean()
 *     ...
 *     minifyEnabled enableMinifyInReleaseBuilds
 *
 * It defaults to false, so every ConPaws release so far has shipped unminified.
 * The property has to be set from a plugin rather than by editing
 * `android/gradle.properties` directly, because `android/` is regenerated by
 * every prebuild -- the same reason `withUploadSigning` exists.
 *
 * `expo-build-properties` would also do this, but it is not a dependency here
 * and its option is named `enableProguardInReleaseBuilds`, which is not the
 * property this template reads. Setting the property directly avoids both the
 * new dependency and the name mismatch.
 *
 * WHAT THIS IS AND IS NOT WORTH
 *
 * R8 shrinks and obfuscates the *dex*. It does not touch native libraries, and
 * the ConPaws bundle is dominated by four ABIs of `.so` -- so do not expect the
 * 78 MB AAB to drop dramatically. Measure the delta rather than assuming it;
 * that is why this is a separate, revertible commit.
 *
 * Play receives the mapping automatically: AGP writes it into the bundle at
 * `BUNDLE-METADATA/com.android.tools.build.obfuscation/proguard.map`, so the
 * "no deobfuscation file" warning in the console resolves itself once this is
 * on, with no upload step.
 *
 * `shrinkResources` is deliberately NOT enabled here. It is a second, separate
 * risk -- it strips resources reached only by name -- and stacking two unproven
 * changes into one release makes a runtime failure twice as hard to attribute.
 *
 * BEFORE SHIPPING A BUILD WITH THIS ON
 *
 * Minification fails at runtime, not at build time. A release build that
 * compiles proves nothing. Install the resulting artifact and exercise the app:
 * import a schedule, open a convention, set a reminder, change language and
 * theme. React Native, Hermes and the Expo modules ship their own `-keep` rules,
 * but anything reached by reflection is exactly what R8 removes quietly.
 */

const MINIFY_KEY = "android.enableMinifyInReleaseBuilds";

module.exports = function withReleaseMinify(config) {
  return withGradleProperties(config, (config) => {
    // Replace rather than append: prebuild can run against an android/ that
    // already carries a previous pass's value.
    const existing = config.modResults.filter(
      (item) => !(item.type === "property" && item.key === MINIFY_KEY),
    );

    config.modResults = [
      ...existing,
      { type: "property", key: MINIFY_KEY, value: "true" },
    ];

    return config;
  });
};
